# Change these first
owner: CSSUDII # Your GitHub username
repo: uptime # Your Github repository name

# Add your sites here
sites:
  - name: WE-BT16 Website
    url: https://we-bt16.netlify.app
  - name: PM2
    url: https://app.pm2.io
  - name: WE-BT16 Discord Bot (API)
    url: https://834fc166c81e.ngrok.io
  - name: WE-BT16 Discord Bot (WebHook)
    url: https://eyes-syndrome-horizontal-shaw.trycloudflare.com
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CSSUDI Monit
  introTitle: "The Status Page for CSSUDII"
  introMessage: All the main CSSUDII projects status will be here!
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
